#!/usr/bin/env bash
# extract.sh — Developer-run script that reads the live CyDo database and
# JSONL session files, then writes fixture files into fixtures/.
#
# Run from any directory:
#   /path/to/extract.sh
#
# Requires: sqlite3, python3, standard Unix tools.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FIXTURES_DIR="$SCRIPT_DIR/fixtures"
SESSIONS_DIR="$FIXTURES_DIR/sessions"

DB_PATH="$SCRIPT_DIR/../../../data/cydo.db"

SOURCE_PATH_CYDO="/home/vladimir/work/cydo"
SOURCE_PATH_AE="/home/vladimir/work/ae-container/ae"
TARGET_PATH_CYDO="/tmp/ws/cydo"
TARGET_PATH_AE="/tmp/ws/ae"

# JSONL source dirs (mangled source paths)
JSONL_DIR_CYDO="$HOME/.claude/projects/-home-vladimir-work-cydo"
JSONL_DIR_AE="$HOME/.claude/projects/-home-vladimir-work-ae-container-ae"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

mangle_path() {
    # Convert /absolute/path to -absolute-path (replace / and . with -)
    # This matches the backend's historyPath() mangling in claude.d
    echo "$1" | tr '/.' '-'
}

# ---------------------------------------------------------------------------
# Phase 1: Export task trees and generate init.sql
# ---------------------------------------------------------------------------

echo "Exporting task trees from $DB_PATH..."

mkdir -p "$FIXTURES_DIR"

python3 - "$DB_PATH" "$FIXTURES_DIR" <<'PYEOF'
import sqlite3
import sys
import os

db_path = sys.argv[1]
fixtures_dir = sys.argv[2]

source_to_target = {
    '/home/vladimir/work/cydo': '/tmp/ws/cydo',
    '/home/vladimir/work/ae-container/ae': '/tmp/ws/ae',
}

# Status overrides (correction: 1689 must be 'active', not 'alive')
status_overrides = {
    1658: 'alive',
    1676: 'waiting',
    1677: 'waiting',
    1689: 'active',
}

root_tids = [1658, 1039]

conn = sqlite3.connect(db_path)
conn.row_factory = sqlite3.Row
cur = conn.cursor()

# Collect all task IDs in the subtrees
all_tids = set()
for root_tid in root_tids:
    cur.execute('''
        WITH RECURSIVE tree(tid) AS (
            SELECT ?
            UNION ALL
            SELECT t.tid FROM tasks t JOIN tree ON t.parent_tid = tree.tid
        )
        SELECT tid FROM tree
    ''', (root_tid,))
    for row in cur.fetchall():
        all_tids.add(row[0])

# Fetch all task rows
tid_list = ','.join(str(t) for t in sorted(all_tids))
cur.execute(f'''
    SELECT tid, agent_session_id, description, task_type, parent_tid,
           relation_type, workspace, project_path, title, status,
           agent_type, draft, result_text
    FROM tasks WHERE tid IN ({tid_list})
    ORDER BY tid
''')
rows = cur.fetchall()

def q(s):
    s = s or ''
    return "'" + s.replace("'", "''") + "'"

output_lines = [
    '-- Generated by extract.sh',
    '-- Seed data for CyDo screenshot derivation',
    '',
    '-- Task rows',
]

for row in rows:
    tid = row['tid']
    agent_session_id = row['agent_session_id'] or ''
    description = row['description'] or ''
    task_type = row['task_type'] or 'conversation'
    parent_tid = row['parent_tid']
    relation_type = row['relation_type'] or ''
    workspace = row['workspace'] or ''
    project_path = row['project_path'] or ''
    title = row['title'] or ''
    status = status_overrides.get(tid, row['status'] or 'completed')
    agent_type = row['agent_type'] or 'claude'
    has_worktree = 0
    archived = 0
    draft = row['draft'] or ''
    result_text = row['result_text'] or ''

    # Mangle project_path
    for src, tgt in source_to_target.items():
        if project_path == src:
            project_path = tgt
            break
        elif project_path.startswith(src + '/'):
            project_path = tgt + project_path[len(src):]
            break

    parent_val = str(parent_tid) if parent_tid is not None else 'NULL'

    line = (
        f'INSERT INTO tasks (tid, agent_session_id, description, task_type, parent_tid, '
        f'relation_type, workspace, project_path, title, status, worktree_path, has_worktree, '
        f'agent_type, archived, draft, result_text) VALUES ('
        f'{tid}, {q(agent_session_id)}, {q(description)}, {q(task_type)}, {parent_val}, '
        f'{q(relation_type)}, {q(workspace)}, {q(project_path)}, {q(title)}, {q(status)}, '
        f'{q("")}, {has_worktree}, {q(agent_type)}, {archived}, {q(draft)}, {q(result_text)});'
    )
    output_lines.append(line)

output_lines += [
    '',
    '-- Dependencies for waiting chain',
    'INSERT INTO task_deps (parent_tid, child_tid) VALUES (1676, 1677);',
    'INSERT INTO task_deps (parent_tid, child_tid) VALUES (1677, 1689);',
    '',
]

conn.close()

os.makedirs(fixtures_dir, exist_ok=True)
init_sql_path = os.path.join(fixtures_dir, 'init.sql')
with open(init_sql_path, 'w') as f:
    f.write('\n'.join(output_lines))
print(f'Written {init_sql_path} ({len(rows)} task rows)')
PYEOF

# ---------------------------------------------------------------------------
# Phase 2: Extract JSONL files
# ---------------------------------------------------------------------------

echo "Extracting JSONL files..."

MANGLED_CYDO="$(mangle_path "$TARGET_PATH_CYDO")"
MANGLED_AE="$(mangle_path "$TARGET_PATH_AE")"

mkdir -p "$SESSIONS_DIR/$MANGLED_CYDO"
mkdir -p "$SESSIONS_DIR/$MANGLED_AE"

# Task 1658 — real JSONL, truncate at line 100
head -100 "$JSONL_DIR_CYDO/ee043871-4594-412d-ae25-c41bc3774a02.jsonl" \
    > "$SESSIONS_DIR/$MANGLED_CYDO/ee043871-4594-412d-ae25-c41bc3774a02.jsonl"
echo "  sessions/$MANGLED_CYDO/ee043871-...jsonl (100 lines)"

# Task 1039 — real JSONL, truncate at line 488
head -488 "$JSONL_DIR_AE/56d46e0a-d8d4-4dbf-8060-c920c87e995b.jsonl" \
    > "$SESSIONS_DIR/$MANGLED_AE/56d46e0a-d8d4-4dbf-8060-c920c87e995b.jsonl"
echo "  sessions/$MANGLED_AE/56d46e0a-...jsonl (488 lines)"

# Synthetic JSONLs — tasks 1676, 1677, 1689 (first 19 lines of 1658's JSONL)
SYNTH_SRC="$JSONL_DIR_CYDO/ee043871-4594-412d-ae25-c41bc3774a02.jsonl"

head -19 "$SYNTH_SRC" > "$SESSIONS_DIR/$MANGLED_CYDO/a0d26783-a3c8-41e2-996b-9f74c01f173f.jsonl"
echo "  sessions/$MANGLED_CYDO/a0d26783-...jsonl (synthetic, 19 lines)"

head -19 "$SYNTH_SRC" > "$SESSIONS_DIR/$MANGLED_CYDO/97d06ae2-b61e-49a8-9417-feb511e093f9.jsonl"
echo "  sessions/$MANGLED_CYDO/97d06ae2-...jsonl (synthetic, 19 lines)"

head -19 "$SYNTH_SRC" > "$SESSIONS_DIR/$MANGLED_CYDO/d202b296-faf4-4714-bcfe-e2d6e7b8c1c5.jsonl"
echo "  sessions/$MANGLED_CYDO/d202b296-...jsonl (synthetic, 19 lines)"

# ---------------------------------------------------------------------------
# Phase 3: Validate
# ---------------------------------------------------------------------------

echo ""
echo "Validating..."

check_jsonl() {
    local f="$1"
    if [ ! -f "$f" ]; then
        echo "ERROR: Missing JSONL: $f"
        exit 1
    fi
    local last_type
    last_type=$(tail -1 "$f" | python3 -c "import sys,json; print(json.loads(sys.stdin.read().strip()).get('type','?'))")
    if [ "$last_type" != "assistant" ]; then
        echo "WARNING: Last line of $(basename "$f") is '$last_type' (expected 'assistant')"
    else
        echo "  OK: $(basename "$f") ends on assistant turn"
    fi
}

check_jsonl "$SESSIONS_DIR/$MANGLED_CYDO/ee043871-4594-412d-ae25-c41bc3774a02.jsonl"
check_jsonl "$SESSIONS_DIR/$MANGLED_CYDO/a0d26783-a3c8-41e2-996b-9f74c01f173f.jsonl"
check_jsonl "$SESSIONS_DIR/$MANGLED_CYDO/97d06ae2-b61e-49a8-9417-feb511e093f9.jsonl"
check_jsonl "$SESSIONS_DIR/$MANGLED_CYDO/d202b296-faf4-4714-bcfe-e2d6e7b8c1c5.jsonl"
check_jsonl "$SESSIONS_DIR/$MANGLED_AE/56d46e0a-d8d4-4dbf-8060-c920c87e995b.jsonl"

echo ""
echo "Done! Fixtures written to $FIXTURES_DIR"
